version: '3.8'

services:
  app:
    build:
      context: .  # This tells Docker to use the current directory as context for the build.
      dockerfile: Dockerfile  # Explicitly use the Dockerfile you provided.
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000:8000"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    command: >
      bash -c "
        composer install &&
        cp .env .env.backup &&
        php artisan config:clear &&
        php artisan key:generate &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan make:filament-user --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

