version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000:8000"  # internal:external
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public  # Ensures Apache can serve static files
    env_file:
      - .env
    command: >
      bash -c "
        composer install &&
        cp .env .env.backup &&
        php artisan config:clear &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
